### ISSUE TITLE
issue while compiling

### ISSUE THREAD

**Issue by mohammadfarazi** [c-hofer/nips2017#5]
Hi,

I have a really hard time to run the provided code. I had many errors, and I fixed some but now I am stuck at the following error:

Traceback (most recent call last):
  File "/home/mfarazi/nips2017/animal.py", line 46, in <module>
    result = experiment(provider_path)
  File "/home/mfarazi/nips2017/src/animal/experiments.py", line 170, in experiment
    model = MyModel(subscripted_views)
  File "/home/mfarazi/nips2017/src/animal/experiments.py", line 71, in __init__
    sharpness_init=torch.ones(n_elements, 2) * 4)
  File "/home/mfarazi/nips2017/src/sharedCode/experiments.py", line 161, in __init__
    self.slayers = [SLayer(n_elements, point_dim, center_init, sharpness_init) for i in range(n_directions)]
  File "/home/mfarazi/nips2017/src/sharedCode/experiments.py", line 161, in <listcomp>
    self.slayers = [SLayer(n_elements, point_dim, center_init, sharpness_init) for i in range(n_directions)]
TypeError: 'module' object is not callable

I use ubuntu with Python 3.6, and PyTorch 1.13. I also downgraded my PyTorch as well, but it did not work. Could you please help me on how to run this code?

**Comment by rkwitt** [comment]
Please checkout the repository

https://github.com/c-hofer/jmlr_2019

which contains (PyTorch 1.4) compatible code for a much more extended JMLR version of the NIPS '17 paper.
